export const initialUsers = [
  {
    name: "Pooja Swarupji",
    phone: "9825012345",
    email: "admin.super@harisumiran.org",
    role: "super_admin",
    passcodeHash: "3690",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "super_admin",
        title: "Super Administrator",
        gujaratiTitle: "મુખ્ય વહીવટકર્તા",
        scope: {},
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
  {
    name: "Nitinbhai Patel",
    phone: "9825023456",
    email: "harisumiran369@gmail.com",
    role: "mandir_admin",
    passcodeHash: "3690",
    department: "Operations & Administration",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "mandir_admin",
        title: "Mandir Administrator",
        gujaratiTitle: "મંદિર વહીવટકર્તા",
        scope: {},
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
  {
    name: "Rameshbhai Patel",
    phone: "9825056789",
    email: "ramesh.patel@gmail.com",
    role: "family_captain",
    passcodeHash: "3690",
    memberId: "MEM-NAD-001",
    familyId: "FAM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    isCaptain: true,
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "regular_member",
        title: "Mandir Member",
        gujaratiTitle: "મંદિર સભ્ય",
        scope: { familyId: "FAM-NAD-001" },
        active: true,
        assignedAt: new Date(),
      },
      {
        type: "thal_captain",
        title: "Family Thal Captain",
        gujaratiTitle: "પરિવાર થાળ કેપ્ટન",
        scope: { familyId: "FAM-NAD-001" },
        active: true,
        assignedAt: new Date(),
      },
      {
        type: "main_cook",
        title: "Mahaprasad Kitchen Lead",
        gujaratiTitle: "મહાપ્રસાદ રસોઈ સેવા પ્રમુખ",
        scope: { department: "Kitchen (Mahaprasad)" },
        active: true,
        assignedAt: new Date(),
      },
      {
        type: "car_owner",
        title: "Mandir Transport Driver (Car Owner)",
        gujaratiTitle: "વાહન સેવા (કાર માલિક)",
        scope: { zone: "North Nadiad" },
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
  {
    name: "Jaimin Trivedi",
    phone: "9825045678",
    email: "jaimin.trivedi@harisumiran.org",
    role: "karyakarta",
    passcodeHash: "3690",
    memberId: "MEM-NAD-005",
    familyId: "FAM-NAD-003",
    familyName: "Trivedi Parivar (Hareshbhai)",
    department: "Sabha & Follow-up",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "regular_member",
        title: "Mandir Member",
        gujaratiTitle: "મંદિર સભ્ય",
        scope: { familyId: "FAM-NAD-003" },
        active: true,
        assignedAt: new Date(),
      },
      {
        type: "sabha_karyakarta",
        title: "Youth Male Sabha Karyakarta (North & Central Nadiad)",
        gujaratiTitle: "યુવક સભા કાર્યકર્તા (ઉત્તર અને મધ્ય નડિયાદ)",
        scope: {
          sabhaType: "Youth Male",
          zone: "North Nadiad",
        },
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
  {
    name: "Devansh Patel",
    phone: "9825067890",
    email: "devansh.patel@gmail.com",
    role: "family_member",
    passcodeHash: "3690",
    memberId: "MEM-NAD-003",
    familyId: "FAM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    isCaptain: false,
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "regular_member",
        title: "Youth Member",
        gujaratiTitle: "યુવા સભ્ય",
        scope: { familyId: "FAM-NAD-001", sabhaType: "Youth Male" },
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
  {
    name: "Dipakbhai Shah",
    phone: "9825034567",
    email: "dipak.shah@harisumiran.org",
    role: "dept_head",
    passcodeHash: "3690",
    department: "Kitchen (Mahaprasad)",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
    responsibilities: [
      {
        type: "main_cook",
        title: "Head Chef / Kitchen In-Charge",
        gujaratiTitle: "મુખ્ય રસોઈયા",
        scope: { department: "Kitchen (Mahaprasad)" },
        active: true,
        assignedAt: new Date(),
      },
    ],
  },
];

export const initialFamilies = [
  {
    familyCode: "FAM-NAD-001",
    name: "Patel Household (Rameshbhai)",
    gujaratiName: "પટેલ પરિવાર (રમેશભાઈ)",
    captainName: "Rameshbhai Patel",
    phone: "9825056789",
    address: "14, Shanti Niketan Society, Station Road",
    area: "Station Road",
    zone: "North Nadiad",
    memberCount: 3,
    engagementLevel: "High",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 2 * 86400000),
    notes: "Regular attendees of Sunday Evening Sabha. Dedicated to Kitchen Seva.",
  },
  {
    familyCode: "FAM-NAD-002",
    name: "Shah Family (Mukeshbhai)",
    gujaratiName: "શાહ પરિવાર (મુકેશભાઈ)",
    captainName: "Mukeshbhai Shah",
    phone: "9825098765",
    address: "B-202, Gokul Heights, Vaniyavad",
    area: "Vaniyavad",
    zone: "Central Nadiad",
    memberCount: 4,
    engagementLevel: "Medium",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 5 * 86400000),
    notes: "Assigned for upcoming Thal turn.",
  },
  {
    familyCode: "FAM-NAD-003",
    name: "Trivedi Parivar (Hareshbhai)",
    gujaratiName: "ત્રિવેદી પરિવાર (હરેશભાઈ)",
    captainName: "Hareshbhai Trivedi",
    phone: "9825076543",
    address: "7, Gayatri Kunj, Santram Mandir Road",
    area: "Santram Road",
    zone: "North Nadiad",
    memberCount: 3,
    engagementLevel: "At-Risk",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 14 * 86400000),
    notes: "Elder surgery recovery. Follow-up case active.",
  },
  {
    familyCode: "FAM-NAD-004",
    name: "Desai Family (Kiritbhai)",
    gujaratiName: "દેસાઈ પરિવાર (કિરીટભાઈ)",
    captainName: "Kiritbhai Desai",
    phone: "9825032109",
    address: "22, Anand Nagar, Dumral Bazar",
    area: "Dumral Bazar",
    zone: "East Nadiad",
    memberCount: 4,
    engagementLevel: "High",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 1 * 86400000),
    notes: "Active in Bal Mandal and youth coaching.",
  },
];

export const initialMembers = [
  {
    memberCode: "MEM-NAD-001",
    familyId: "FAM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    name: "Rameshbhai Patel",
    gujaratiName: "રમેશભાઈ પટેલ",
    dob: "1968-04-12",
    gender: "Male",
    phone: "9825056789",
    email: "ramesh.patel@gmail.com",
    relationship: "Self",
    zone: "North Nadiad",
    area: "Station Road",
    sabhaCategory: "Family Sabha",
    sevaSkills: ["Kitchen / Mahaprasad", "Procurement", "Transportation"],
    attendanceStreak: 18,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
    qrCode: "MEMBER:MEM-NAD-001:RAMESHBHAI",
  },
  {
    memberCode: "MEM-NAD-002",
    familyId: "FAM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    name: "Hansaben Patel",
    gujaratiName: "હંસાબેન પટેલ",
    dob: "1972-08-20",
    gender: "Female",
    phone: "9825056780",
    email: "hansa.patel@gmail.com",
    relationship: "Spouse",
    zone: "North Nadiad",
    area: "Station Road",
    sabhaCategory: "Family Sabha",
    sevaSkills: ["Rangoli & Decoration", "Mahaprasad Preparation"],
    attendanceStreak: 16,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
    qrCode: "MEMBER:MEM-NAD-002:HANSABEN",
  },
  {
    memberCode: "MEM-NAD-003",
    familyId: "FAM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    name: "Devansh Patel",
    gujaratiName: "દેવાંશ પટેલ",
    dob: "2000-11-05",
    gender: "Male",
    phone: "9825067890",
    email: "devansh.patel@gmail.com",
    relationship: "Son",
    zone: "North Nadiad",
    area: "Station Road",
    sabhaCategory: "Youth Male",
    sevaSkills: ["Sound & Broadcast", "Live Streaming", "Youth Coordination"],
    attendanceStreak: 12,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
    qrCode: "MEMBER:MEM-NAD-003:DEVANSH",
  },
  {
    memberCode: "MEM-NAD-004",
    familyId: "FAM-NAD-002",
    familyName: "Shah Family (Mukeshbhai)",
    name: "Mukeshbhai Shah",
    gujaratiName: "મુકેશભાઈ શાહ",
    dob: "1975-01-15",
    gender: "Male",
    phone: "9825098765",
    email: "mukesh.shah@yahoo.com",
    relationship: "Self",
    zone: "Central Nadiad",
    area: "Vaniyavad",
    sabhaCategory: "Family Sabha",
    sevaSkills: ["Accounts & Finance", "Thal Seva"],
    attendanceStreak: 8,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
    qrCode: "MEMBER:MEM-NAD-004:MUKESHBHAI",
  },
  {
    memberCode: "MEM-NAD-005",
    familyId: "FAM-NAD-003",
    familyName: "Trivedi Parivar (Hareshbhai)",
    name: "Hareshbhai Trivedi",
    gujaratiName: "હરેશભાઈ ત્રિવેદી",
    dob: "1962-09-10",
    gender: "Male",
    phone: "9825076543",
    email: "haresh.trivedi@gmail.com",
    relationship: "Self",
    zone: "North Nadiad",
    area: "Santram Road",
    sabhaCategory: "Family Sabha",
    sevaSkills: ["Kirtan Singing", "Sanskrit Shloka"],
    attendanceStreak: 0,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: false,
    qrCode: "MEMBER:MEM-NAD-005:HARESHBHAI",
  },
];

export const initialSabhas = [
  {
    sabhaCode: "SAB-2026-091",
    title: "Sunday Evening Satsang Sabha",
    gujaratiTitle: "રવિવાર સાંજ સત્સંગ સભા",
    type: "Evening Sabha",
    zone: "All Nadiad",
    targetGender: "All",
    date: "2026-09-13",
    startTime: "18:00",
    endTime: "20:00",
    location: "Main Satsang Hall, Nadiad",
    status: "Scheduled",
    expectedCount: 160,
    presentCount: 0,
    checklist: [
      { item: "Microphone & Sound System Checked", completed: true },
      { item: "Mahaprasad Kitchen Readiness Confirmed", completed: true },
      { item: "Live Stream Setup & Camera Check", completed: false },
    ],
    notes: "Discourse on Vachanamrut Gadhada Pratham 1.",
  },
  {
    sabhaCode: "SAB-2026-092",
    title: "Youth Male Sabha (Yuvak Mandal)",
    gujaratiTitle: "યુવક સભા (ઉત્તર નડિયાદ)",
    type: "Youth Male",
    zone: "North Nadiad",
    targetGender: "Male",
    date: "2026-09-13",
    startTime: "19:00",
    endTime: "20:30",
    location: "Youth Sabha Hall, HariPrabodham",
    status: "Scheduled",
    expectedCount: 45,
    presentCount: 0,
    checklist: [
      { item: "Youth Topic Presentation Prepared", completed: true },
      { item: "Q&A Discussion Group Formed", completed: true },
    ],
    notes: "Discussion: Satsang in Professional Life.",
  },
  {
    sabhaCode: "SAB-2026-093",
    title: "Yuvati Sabha (North & Central)",
    gujaratiTitle: "યુવતી સભા",
    type: "Yuvati",
    zone: "Central Nadiad",
    targetGender: "Female",
    date: "2026-09-13",
    startTime: "16:00",
    endTime: "17:30",
    location: "Prarthana Hall, HariPrabodham",
    status: "Scheduled",
    expectedCount: 35,
    presentCount: 0,
    checklist: [{ item: "Seva Planning Discussion Ready", completed: true }],
    notes: "Special session for Yuvati mandal.",
  },
];

export const initialFollowUpCases = [
  {
    caseCode: "CASE-NAD-101",
    familyId: "FAM-NAD-003",
    familyName: "Trivedi Parivar (Hareshbhai)",
    memberId: "MEM-NAD-005",
    memberName: "Hareshbhai Trivedi",
    zone: "North Nadiad",
    sabhaType: "Family Sabha",
    category: "Extended Absence",
    urgency: "Overdue",
    dueDate: "2026-09-10",
    assignedKaryakartaId: "karyakarta-jaimin",
    assignedKaryakartaName: "Jaimin Trivedi",
    status: "Open",
    confidentialNotes: [
      {
        authorName: "Jaimin Trivedi",
        note: "Elder father underwent eye surgery in Ahmedabad. Family missed last 3 sabhas. Planned home visit with prasadi thal.",
        createdAt: new Date(Date.now() - 2 * 86400000),
      },
    ],
    visitPlan: {
      date: "2026-09-14",
      time: "17:30",
      coVisitor: "Nitinbhai Patel",
    },
  },
];

export const initialSevaOpportunities = [
  {
    title: "Sunday Mahaprasad Kitchen Seva",
    gujaratiTitle: "રવિવાર મહાપ્રસાદ રસોઈ સેવા",
    category: "Kitchen",
    department: "Kitchen (Mahaprasad)",
    description: "Preparation of fresh roti, shaak, dal, and rice for 200+ devotees.",
    date: "2026-09-13",
    startTime: "16:00",
    endTime: "19:00",
    location: "Mandir Bhojanshala Kitchen",
    requiredVolunteerCount: 6,
    acceptedVolunteerCount: 3,
    genderEligibility: "All",
    zoneEligibility: "All Nadiad",
    status: "Open",
    leadName: "Dipakbhai Shah",
    leadPhone: "9825034567",
    volunteers: [
      {
        memberId: "MEM-NAD-001",
        memberName: "Rameshbhai Patel",
        phone: "9825056789",
        claimedAt: new Date(Date.now() - 4 * 3600000),
      },
      {
        memberId: "MEM-NAD-002",
        memberName: "Hansaben Patel",
        phone: "9825056780",
        claimedAt: new Date(Date.now() - 3 * 3600000),
      },
    ],
  },
  {
    title: "Audio & Live Stream Console Operation",
    gujaratiTitle: "સાઉન્ડ અને લાઈવ સ્ટ્રીમ કન્સોલ સેવા",
    category: "Sabha Assistance",
    department: "Sound & Broadcast",
    description: "Mixer operation, YouTube streaming monitoring, wireless mic battery checks.",
    date: "2026-09-13",
    startTime: "17:30",
    endTime: "20:00",
    location: "Main Satsang Hall AV Room",
    requiredVolunteerCount: 2,
    acceptedVolunteerCount: 1,
    genderEligibility: "Male",
    zoneEligibility: "All Nadiad",
    status: "Open",
    leadName: "Devansh Patel",
    leadPhone: "9825067890",
    volunteers: [
      {
        memberId: "MEM-NAD-003",
        memberName: "Devansh Patel",
        phone: "9825067890",
        claimedAt: new Date(),
      },
    ],
  },
  {
    title: "Mandir Entry & Parking Traffic Guidance",
    gujaratiTitle: "મંદિર પ્રવેશ અને પાર્કિંગ ટ્રાફિક વ્યવસ્થા",
    category: "Mandir Service",
    department: "Security & Parking",
    description: "Guidance for 2-wheeler and 4-wheeler parking along Station Road gate.",
    date: "2026-09-13",
    startTime: "17:30",
    endTime: "19:30",
    location: "Station Road Gate",
    requiredVolunteerCount: 4,
    acceptedVolunteerCount: 2,
    genderEligibility: "All",
    status: "Open",
    leadName: "Nitinbhai Patel",
    volunteers: [],
  },
];

export const initialRecipes = [
  {
    recipeCode: "REC-001",
    name: "Swaminarayan Khichdi & Kadhi",
    gujaratiName: "સ્વામિનારાયણ ખીચડી અને કઢી",
    category: "Main Course",
    description: "Traditional pure ghee khichdi prepared with rice and moong dal accompanied by spiced Gujarati kadhi.",
    prepTimeMinutes: 45,
    ingredients: [
      { name: "Rice (Kolam/Basmati)", gujaratiName: "ચોખા", quantityPer10People: 1.0, unit: "kg" },
      { name: "Moong Dal (Yellow Split)", gujaratiName: "મૂંગ દાળ", quantityPer10People: 0.5, unit: "kg" },
      { name: "Desi Ghee", gujaratiName: "શુદ્ધ ઘી", quantityPer10People: 0.25, unit: "kg" },
      { name: "Fresh Curd (for Kadhi)", gujaratiName: "તાજું દહીં", quantityPer10People: 0.8, unit: "liter" },
      { name: "Besan (Gram Flour)", gujaratiName: "ચણાનો લોટ", quantityPer10People: 0.15, unit: "kg" },
      { name: "Cumin & Mustard Seeds", gujaratiName: "જીરું અને રાઈ", quantityPer10People: 0.03, unit: "kg" },
      { name: "Ginger & Green Chili", gujaratiName: "આદું અને મરચાં", quantityPer10People: 0.05, unit: "kg" },
    ],
    preparationInstructions: [
      "Wash rice and moong dal thoroughly and soak for 20 minutes.",
      "Heat pure ghee in large steam pot; temper cumin seeds, cloves, and bay leaf.",
      "Add soaked dal-rice with 3x water, salt, and turmeric. Simmer until soft and fragrant.",
      "Whisk curd with besan and water for kadhi; temper with ginger, green chili, curry leaves, and slow boil.",
    ],
  },
  {
    recipeCode: "REC-002",
    name: "Batata Nu Shaak (Potato Curry)",
    gujaratiName: "બટાટાનું શાક",
    category: "Main Course",
    description: "Mildly spiced sattvic potato curry without onion or garlic.",
    prepTimeMinutes: 30,
    ingredients: [
      { name: "Potatoes (Chopped)", gujaratiName: "બટાટા", quantityPer10People: 1.5, unit: "kg" },
      { name: "Groundnut Oil", gujaratiName: "સીંગતેલ", quantityPer10People: 0.15, unit: "liter" },
      { name: "Mustard & Fenugreek Seeds", gujaratiName: "રાઈ-મેથી", quantityPer10People: 0.02, unit: "kg" },
      { name: "Turmeric & Coriander Powder", gujaratiName: "હળદર અને ધાણાજીરું", quantityPer10People: 0.05, unit: "kg" },
      { name: "Fresh Coriander", gujaratiName: "કોથમરી", quantityPer10People: 0.1, unit: "kg" },
    ],
    preparationInstructions: [
      "Boil and cube fresh potatoes.",
      "Heat groundnut oil, add mustard seeds and hing.",
      "Add potato cubes, dry spices, minimal water and simmer for 15 minutes.",
      "Garnish with fresh chopped coriander.",
    ],
  },
];

export const initialTravelRides = [
  {
    rideCode: "RIDE-2026-001",
    title: "Sunday Evening Sabha Ride from Station Road",
    gujaratiTitle: "રવિવાર સાંજ સભા રાઈડ (સ્ટેશન રોડ)",
    driverMemberId: "MEM-NAD-001",
    driverName: "Rameshbhai Patel",
    driverPhone: "9825056789",
    vehicleModel: "Maruti Ertiga (7 Seater)",
    vehicleNumber: "GJ-07-BP-3690",
    totalSeats: 6,
    availableSeats: 4,
    departureTime: "2026-09-13 17:15",
    departureLocation: "Shanti Niketan Society, Station Road Gate",
    destination: "HariPrabodham Mandir, Nadiad",
    routeNotes: "Picking up near Station Road circle and College Road.",
    status: "Scheduled",
    requests: [
      {
        requestId: "REQ-01",
        passengerMemberId: "MEM-NAD-005",
        passengerName: "Hareshbhai Trivedi",
        passengerPhone: "9825076543",
        pickupPoint: "Gayatri Kunj, Santram Road",
        seatsRequested: 1,
        status: "Approved",
        requestedAt: new Date(Date.now() - 5 * 3600000),
        decidedAt: new Date(Date.now() - 4 * 3600000),
      },
    ],
  },
];

export const initialThalSchedules = [
  {
    scheduleCode: "THAL-2026-09-12-M",
    date: "2026-09-12",
    monthPeriod: "2026-09",
    mealType: "Breakfast (Morning Thal)",
    assignedFamilyId: "FAM-NAD-001",
    assignedFamilyName: "Patel Household (Rameshbhai)",
    assignedPhone: "9825056789",
    captainName: "Rameshbhai Patel",
    headcount: 55,
    status: "Assigned",
    specialInstructions: "Puri, Batata Shaak, and Kesar Shrikhand.",
  },
  {
    scheduleCode: "THAL-2026-09-12-E",
    date: "2026-09-12",
    monthPeriod: "2026-09",
    mealType: "Dinner (Evening Thal)",
    assignedFamilyId: "FAM-NAD-002",
    assignedFamilyName: "Shah Family (Mukeshbhai)",
    assignedPhone: "9825098765",
    captainName: "Mukeshbhai Shah",
    headcount: 65,
    status: "Confirmed",
    specialInstructions: "Khichdi, Gujarati Kadhi, and Dudhpak.",
  },
  {
    scheduleCode: "THAL-2026-09-13-M",
    date: "2026-09-13",
    monthPeriod: "2026-09",
    mealType: "Breakfast (Morning Thal)",
    assignedFamilyId: "FAM-NAD-003",
    assignedFamilyName: "Trivedi Parivar (Hareshbhai)",
    assignedPhone: "9825076543",
    captainName: "Hareshbhai Trivedi",
    headcount: 50,
    status: "Assigned",
    swapRequested: true,
    specialInstructions: "Morning prasad with Rotli and Moong Dal.",
  },
];

export const initialThalSwapRequests = [
  {
    thalScheduleId: "THAL-2026-09-13-M",
    originalDate: "2026-09-13",
    mealType: "Breakfast (Morning Thal)",
    requestingFamilyId: "FAM-NAD-003",
    requestingFamilyName: "Trivedi Parivar (Hareshbhai)",
    requestingCaptainName: "Hareshbhai Trivedi",
    swapType: "family_to_family",
    targetFamilyId: "FAM-NAD-001",
    targetFamilyName: "Patel Household (Rameshbhai)",
    targetCaptainName: "Rameshbhai Patel",
    targetCaptainDecision: "Pending",
    suggestedDate: "2026-09-20",
    reason: "Elder surgery recovery. Requesting swap with Patel household.",
    status: "Pending Target Captain",
    createdAt: new Date(Date.now() - 3600000),
  },
];

export const initialNotifications = [
  {
    title: "Thal Swap Request Received",
    gujaratiTitle: "થાળ બદલી માટે વિનંતી મળી",
    message: "Trivedi Parivar (Hareshbhai) has requested a Thal swap with your household for Sunday, 13th Sept.",
    gujaratiMessage: "ત્રિવેદી પરિવારે રવિવાર ૧૩ સપ્ટેમ્બર માટે થાળ બદલીની વિનંતી કરી છે.",
    category: "thal_swap",
    actionType: "SWAP_ACCEPT_REJECT",
    actionPayload: { swapId: "swap-001", scheduleId: "THAL-2026-09-13-M" },
    actionTaken: false,
    read: false,
    createdAt: new Date(),
  },
  {
    title: "Kitchen Seva: Volunteers Needed",
    gujaratiTitle: "રસોઈ સેવા: સ્વયંસેવકોની જરૂર છે",
    message: "Sunday Mahaprasad preparation needs 3 more volunteers from 16:00 to 19:00.",
    gujaratiMessage: "રવિવાર મહાપ્રસાદ રસોઈ માટે ૩ વધુ સ્વયંસેવકોની જરૂર છે.",
    category: "seva_alert",
    actionType: "SEVA_CLAIM",
    actionPayload: { sevaId: "SEVA-KITCHEN-01" },
    actionTaken: false,
    read: false,
    createdAt: new Date(Date.now() - 1800000),
  },
];

// Compatibility datasets for legacy routes
export const initialAssets = [
  {
    assetCode: "AST-001",
    name: "JBL Wireless Sound System",
    category: "Audio/Visual",
    location: "AV Store Room",
    condition: "Good",
    status: "Available",
  },
];

export const initialRoomBookings = [
  {
    roomName: "Dining Hall (Bhojanshala)",
    purpose: "Post-Sabha Mahaprasad",
    bookedBy: "Dipakbhai Shah",
    date: "2026-09-13",
    startTime: "16:00",
    endTime: "20:30",
    attendees: 150,
    status: "Confirmed",
  },
];

export const initialEvents = [
  {
    eventCode: "EVT-2026-001",
    title: "Janmashtami Mahotsav 2026",
    gujaratiTitle: "શ્રીકૃષ્ણ જન્માષ્ટમી મહોત્સવ",
    date: "2026-09-13",
    location: "Mandir Ground, Nadiad",
    description: "Annual Janmashtami Mahotsav with special darshan, palna utsav, and kirtan bhakti.",
    capacity: 500,
    registeredCount: 320,
    status: "Live",
    committeeLeads: [],
    tasks: [],
  },
];

export const initialAnnouncements = [
  {
    title: "Special Sunday Sabha Time Reminder",
    gujaratiTitle: "રવિવાર સભા સમય અંગે સૂચના",
    body: "Please note Sunday Evening Sabha commences at 6:00 PM IST.",
    gujaratiBody: "રવિવાર સાંજ સભા સાંજે ૬:૦૦ કલાકે શરૂ થશે.",
    targetAudience: "Everyone",
    channels: ["App Push"],
    status: "Sent",
    authorName: "Mandir Office",
    stats: { sentCount: 150, deliveredCount: 148, openedCount: 120 },
    createdAt: new Date(),
  },
];

export const initialAuditLogs = [
  {
    actorId: "usr-admin-01",
    actorName: "Nitinbhai Patel",
    actorRole: "mandir_admin",
    action: "UPDATE_THAL_SCHEDULE",
    module: "Thal",
    description: "Published monthly Thal schedule for September 2026.",
    createdAt: new Date(),
  },
];

export const initialSevaRosters = [
  {
    opportunityTitle: "Sunday Mahaprasad Kitchen Seva",
    department: "Kitchen (Mahaprasad)",
    date: "2026-09-13",
    shiftStartTime: "16:00",
    shiftEndTime: "19:00",
    volunteerName: "Rameshbhai Patel",
    volunteerPhone: "9825056789",
    status: "Checked In",
    checkInTime: new Date(),
  },
];
