export const initialUsers = [
  {
    name: "Pooja Swarupji",
    phone: "9825012345",
    email: "admin.super@harisumiran.org",
    role: "super_admin",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
  },
  {
    name: "Nitinbhai Patel",
    phone: "9825023456",
    email: "nitin.patel@harisumiran.org",
    role: "mandir_admin",
    department: "Operations & Administration",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
  },
  {
    name: "Dipakbhai Shah",
    phone: "9825034567",
    email: "dipak.shah@harisumiran.org",
    role: "dept_head",
    department: "Kitchen (Mahaprasad)",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
  },
  {
    name: "Jaimin Trivedi",
    phone: "9825045678",
    email: "jaimin.trivedi@harisumiran.org",
    role: "karyakarta",
    department: "Sabha & Follow-up",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: true,
    active: true,
  },
  {
    name: "Rameshbhai Patel",
    phone: "9825056789",
    email: "ramesh.patel@gmail.com",
    role: "family_captain",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: false,
    active: true,
  },
  {
    name: "Devansh Patel",
    phone: "9825067890",
    email: "devansh.patel@gmail.com",
    role: "family_member",
    mandir: "HariPrabodham, Nadiad",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    biometricEnabled: false,
    active: true,
  },
];

export const initialFamilies = [
  {
    familyCode: "FAM-NAD-001",
    name: "Patel Household (Rameshbhai)",
    gujaratiName: "પટેલ પરિવાર (રમેશભાઈ)",
    captainName: "Rameshbhai Patel",
    phone: "9825056789",
    address: "14, Shanti Niketan Society, Station Road",
    area: "Station Road",
    zone: "North Nadiad",
    memberCount: 4,
    engagementLevel: "High",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 2 * 86400000),
    notes: "Regular attendees of Sunday Evening Sabha. Dedicated to Kitchen Seva.",
  },
  {
    familyCode: "FAM-NAD-002",
    name: "Shah Family (Mukeshbhai)",
    gujaratiName: "શાહ પરિવાર (મુકેશભાઈ)",
    captainName: "Mukeshbhai Shah",
    phone: "9825098765",
    address: "B-202, Gokul Heights, Vaniyavad",
    area: "Vaniyavad",
    zone: "Central Nadiad",
    memberCount: 5,
    engagementLevel: "Medium",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 5 * 86400000),
    notes: "Assigned for upcoming Thal turn next Saturday.",
  },
  {
    familyCode: "FAM-NAD-003",
    name: "Trivedi Parivar (Hareshbhai)",
    gujaratiName: "ત્રિવેદી પરિવાર (હરેશભાઈ)",
    captainName: "Hareshbhai Trivedi",
    phone: "9825076543",
    address: "7, Gayatri Kunj, Santram Mandir Road",
    area: "Santram Road",
    zone: "South Nadiad",
    memberCount: 3,
    engagementLevel: "At-Risk",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 14 * 86400000),
    notes: "Missed last 3 sabhas due to elder surgery. Follow-up case active.",
  },
  {
    familyCode: "FAM-NAD-004",
    name: "Desai Family (Kiritbhai)",
    gujaratiName: "દેસાઈ પરિવાર (કિરીટભાઈ)",
    captainName: "Kiritbhai Desai",
    phone: "9825032109",
    address: "22, Anand Nagar, Dumral Bazar",
    area: "Dumral Bazar",
    zone: "East Nadiad",
    memberCount: 4,
    engagementLevel: "High",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 1 * 86400000),
    notes: "Active in Bal Mandal and youth coaching.",
  },
  {
    familyCode: "FAM-NAD-005",
    name: "Bhatt Parivar (Pankajbhai)",
    gujaratiName: "ભટ્ટ પરિવાર (પંકજભાઈ)",
    captainName: "Pankajbhai Bhatt",
    phone: "9825011223",
    address: "45, Swaminarayan Nagar, College Road",
    area: "College Road",
    zone: "North Nadiad",
    memberCount: 6,
    engagementLevel: "Medium",
    status: "Active",
    lastInteractionAt: new Date(Date.now() - 8 * 86400000),
    notes: "Audio-visual volunteer support.",
  },
  {
    familyCode: "FAM-NAD-006",
    name: "Vora Family (Ashokbhai)",
    gujaratiName: "વોરા પરિવાર (અશોકભાઈ)",
    captainName: "Ashokbhai Vora",
    phone: "9825044556",
    address: "12, Vallabh Park, Petlad Road",
    area: "Petlad Road",
    zone: "West Nadiad",
    memberCount: 3,
    engagementLevel: "Low",
    status: "Duplicate Flagged",
    lastInteractionAt: new Date(Date.now() - 20 * 86400000),
    notes: "Possible duplicate registration with Vora Ashok R.",
  },
];

export const initialMembers = [
  {
    memberCode: "MEM-NAD-001",
    familyName: "Patel Household (Rameshbhai)",
    name: "Rameshbhai Patel",
    gujaratiName: "રમેશભાઈ પટેલ",
    dob: "1968-04-12",
    gender: "Male",
    phone: "9825056789",
    email: "ramesh.patel@gmail.com",
    relationship: "Head of Family",
    sevaSkills: ["Kitchen / Mahaprasad", "Procurement", "Crowd Guidance"],
    attendanceStreak: 18,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
  },
  {
    memberCode: "MEM-NAD-002",
    familyName: "Patel Household (Rameshbhai)",
    name: "Hansaben Patel",
    gujaratiName: "હંસાબેન પટેલ",
    dob: "1972-08-20",
    gender: "Female",
    phone: "9825056780",
    email: "hansa.patel@gmail.com",
    relationship: "Spouse",
    sevaSkills: ["Rangoli & Decoration", "Mahaprasad Preparation"],
    attendanceStreak: 16,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
  },
  {
    memberCode: "MEM-NAD-003",
    familyName: "Patel Household (Rameshbhai)",
    name: "Devansh Patel",
    gujaratiName: "દેવાંશ પટેલ",
    dob: "2000-11-05",
    gender: "Male",
    phone: "9825067890",
    email: "devansh.patel@gmail.com",
    relationship: "Son",
    sevaSkills: ["Sound & Broadcast", "Live Streaming", "Youth Coordination"],
    attendanceStreak: 12,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
  },
  {
    memberCode: "MEM-NAD-004",
    familyName: "Shah Family (Mukeshbhai)",
    name: "Mukeshbhai Shah",
    gujaratiName: "મુકેશભાઈ શાહ",
    dob: "1975-01-15",
    gender: "Male",
    phone: "9825098765",
    email: "mukesh.shah@yahoo.com",
    relationship: "Head of Family",
    sevaSkills: ["Accounts & Finance", "Thal Seva"],
    attendanceStreak: 8,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
  },
  {
    memberCode: "MEM-NAD-005",
    familyName: "Trivedi Parivar (Hareshbhai)",
    name: "Hareshbhai Trivedi",
    gujaratiName: "હરેશભાઈ ત્રિવેદી",
    dob: "1962-09-10",
    gender: "Male",
    phone: "9825076543",
    email: "haresh.trivedi@gmail.com",
    relationship: "Head of Family",
    sevaSkills: ["Kirtan Singing", "Sanskrit Shloka"],
    attendanceStreak: 0,
    verificationStatus: "Pending Verification",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: false,
  },
  {
    memberCode: "MEM-NAD-006",
    familyName: "Desai Family (Kiritbhai)",
    name: "Kiritbhai Desai",
    gujaratiName: "કિરીટભાઈ દેસાઈ",
    dob: "1980-03-25",
    gender: "Male",
    phone: "9825032109",
    email: "kirit.desai@gmail.com",
    relationship: "Head of Family",
    sevaSkills: ["Bal Mandal Coaching", "First Aid"],
    attendanceStreak: 15,
    verificationStatus: "Verified",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    communicationConsent: true,
    photoConsent: true,
  },
];

export const initialSabhas = [
  {
    sabhaCode: "SAB-2026-081",
    title: "Sunday Evening Satsang Sabha",
    gujaratiTitle: "રવિવાર સાંજ સત્સંગ સભા",
    type: "Evening Sabha",
    date: "2026-08-23",
    startTime: "18:00",
    endTime: "20:00",
    location: "Main Satsang Hall, Nadiad",
    status: "Live",
    expectedCount: 140,
    presentCount: 94,
    checklist: [
      { item: "Microphone & Sound System Checked", completed: true },
      { item: "Stage Floral Decoration Completed", completed: true },
      { item: "Mahaprasad Kitchen Readiness Confirmed", completed: true },
      { item: "Live Stream Setup & Camera Check", completed: true },
      { item: "Shoe Stand & Parking Volunteer Deployed", completed: true },
    ],
    notes: "Special discourse on Vachanamrut Gadhada Pratham 1.",
  },
  {
    sabhaCode: "SAB-2026-082",
    title: "Saturday Morning Dhyan & Prarthana",
    gujaratiTitle: "શનિવાર સવાર ધ્યાન અને પ્રાર્થના",
    type: "Morning Sabha",
    date: "2026-08-22",
    startTime: "06:30",
    endTime: "08:00",
    location: "Prarthana Hall, Nadiad",
    status: "Completed",
    expectedCount: 60,
    presentCount: 52,
    checklist: [
      { item: "Chanting Audio Track Ready", completed: true },
      { item: "Prasad Distribution Prepared", completed: true },
    ],
    notes: "Peaceful morning session with dhyan.",
  },
  {
    sabhaCode: "SAB-2026-083",
    title: "Janmashtami Mahotsav Sabha",
    gujaratiTitle: "શ્રીકૃષ્ણ જન્માષ્ટમી મહોત્સવ સભા",
    type: "Special Mahotsav",
    date: "2026-08-30",
    startTime: "17:30",
    endTime: "21:30",
    location: "Mandir Ground & Sabhagruh",
    status: "Scheduled",
    expectedCount: 350,
    presentCount: 0,
    checklist: [
      { item: "Palna Darshan Setup", completed: false },
      { item: "Nand Utsav Drama Rehearsal", completed: true },
      { item: "Special Security Barrier Layout", completed: false },
      { item: "Prasad Packaging (350+ Boxes)", completed: false },
    ],
    notes: "Major annual festival. Registration QR passes enabled.",
  },
];

export const initialFollowUpCases = [
  {
    caseCode: "CASE-NAD-101",
    familyName: "Trivedi Parivar (Hareshbhai)",
    category: "Extended Absence",
    urgency: "Overdue",
    dueDate: "2026-08-20",
    assignedKaryakartaId: "karyakarta-jaimin",
    assignedKaryakartaName: "Jaimin Trivedi",
    status: "Open",
    confidentialNotes: [
      {
        authorName: "Jaimin Trivedi",
        note: "Elder father underwent cataract surgery in Ahmedabad. Family could not attend last 3 sabhas. Plan a home visit with Mahaprasad.",
        createdAt: new Date(Date.now() - 4 * 86400000),
      },
    ],
    visitPlan: {
      date: "2026-08-24",
      time: "17:00",
      coVisitor: "Nitinbhai Patel",
    },
  },
  {
    caseCode: "CASE-NAD-102",
    familyName: "Vora Family (Ashokbhai)",
    category: "Health & Wellbeing",
    urgency: "Due Today",
    dueDate: "2026-08-23",
    assignedKaryakartaId: "karyakarta-jaimin",
    assignedKaryakartaName: "Jaimin Trivedi",
    status: "Visit Planned",
    confidentialNotes: [
      {
        authorName: "Jaimin Trivedi",
        note: "Follow up regarding member duplicate entry and confirm updated contact number for WhatsApp alerts.",
        createdAt: new Date(Date.now() - 1 * 86400000),
      },
    ],
    visitPlan: {
      date: "2026-08-23",
      time: "19:30",
    },
  },
  {
    caseCode: "CASE-NAD-103",
    familyName: "Bhatt Parivar (Pankajbhai)",
    category: "Special Seva Care",
    urgency: "Upcoming",
    dueDate: "2026-08-28",
    assignedKaryakartaId: "karyakarta-jaimin",
    assignedKaryakartaName: "Jaimin Trivedi",
    status: "Open",
    confidentialNotes: [
      {
        authorName: "Nitinbhai Patel",
        note: "Youth member interested in sound engineering seva for Janmashtami mahotsav. Connect with Sound Lead Devansh.",
        createdAt: new Date(Date.now() - 2 * 86400000),
      },
    ],
  },
];

export const initialSevaOpportunities = [
  {
    title: "Sunday Mahaprasad Kitchen Seva",
    gujaratiTitle: "રવિવાર મહાપ્રસાદ રસોઈ સેવા",
    department: "Kitchen (Mahaprasad)",
    description: "Preparation of fresh roti, shaak, dal, and rice for 200+ devotees.",
    skillsRequired: ["Cooking", "Vegetable Chopping", "Cleanliness"],
    timeCommitment: "3 Hours (16:00 - 19:00)",
    totalSlots: 10,
    filledSlots: 8,
    status: "Open",
    leadName: "Dipakbhai Shah",
  },
  {
    title: "Audio & Live Stream Console Operation",
    gujaratiTitle: "સાઉન્ડ અને લાઈવ સ્ટ્રીમ કન્સોલ સેવા",
    department: "Sound & Broadcast",
    description: "Mixer operation, YouTube streaming monitoring, mic battery replacements.",
    skillsRequired: ["Audio Mixing", "OBS / Streamyard", "Troubleshooting"],
    timeCommitment: "2.5 Hours (17:30 - 20:00)",
    totalSlots: 3,
    filledSlots: 2,
    status: "Open",
    leadName: "Devansh Patel",
  },
  {
    title: "Mandir Entry & Parking Traffic Guidance",
    gujaratiTitle: "મંદિર પ્રવેશ અને પાર્કિંગ ટ્રાફિક વ્યવસ્થા",
    department: "Security & Parking",
    description: "Guidance for 2-wheeler and 4-wheeler parking along Station Road gate.",
    skillsRequired: ["Crowd Control", "Polite Communication"],
    timeCommitment: "2 Hours (17:30 - 19:30)",
    totalSlots: 6,
    filledSlots: 6,
    status: "Full",
    leadName: "Kiritbhai Desai",
  },
  {
    title: "Bal Mandal Creative Learning Activities",
    gujaratiTitle: "બાળ મંડળ પ્રવૃત્તિ સેવા",
    department: "Bal Mandal & Youth",
    description: "Moral storytelling, quiz facilitation, and drawing sessions for children aged 5-12.",
    skillsRequired: ["Teaching", "Storytelling", "Patience"],
    timeCommitment: "2 Hours (18:00 - 20:00)",
    totalSlots: 4,
    filledSlots: 3,
    status: "Open",
    leadName: "Kiritbhai Desai",
  },
];

export const initialSevaRosters = [
  {
    opportunityTitle: "Sunday Mahaprasad Kitchen Seva",
    department: "Kitchen (Mahaprasad)",
    date: "2026-08-23",
    shiftStartTime: "16:00",
    shiftEndTime: "19:00",
    volunteerName: "Rameshbhai Patel",
    volunteerPhone: "9825056789",
    status: "Checked In",
    checkInTime: new Date(Date.now() - 45 * 60000),
  },
  {
    opportunityTitle: "Sunday Mahaprasad Kitchen Seva",
    department: "Kitchen (Mahaprasad)",
    date: "2026-08-23",
    shiftStartTime: "16:00",
    shiftEndTime: "19:00",
    volunteerName: "Hansaben Patel",
    volunteerPhone: "9825056780",
    status: "Checked In",
    checkInTime: new Date(Date.now() - 40 * 60000),
  },
  {
    opportunityTitle: "Audio & Live Stream Console Operation",
    department: "Sound & Broadcast",
    date: "2026-08-23",
    shiftStartTime: "17:30",
    shiftEndTime: "20:00",
    volunteerName: "Devansh Patel",
    volunteerPhone: "9825067890",
    status: "Checked In",
    checkInTime: new Date(Date.now() - 15 * 60000),
  },
  {
    opportunityTitle: "Mandir Entry & Parking Traffic Guidance",
    department: "Security & Parking",
    date: "2026-08-23",
    shiftStartTime: "17:30",
    shiftEndTime: "19:30",
    volunteerName: "Kiritbhai Desai",
    volunteerPhone: "9825032109",
    status: "Assigned",
  },
];

export const initialAssets = [
  {
    assetCode: "AST-SND-01",
    name: "Shure Wireless Handheld Mic Set (2x)",
    category: "Audio/Visual",
    location: "Sound Booth Cabinet 1",
    condition: "Excellent",
    status: "In Use",
    currentHolder: "Devansh Patel",
    expectedReturnDate: "2026-08-23",
    notes: "Batteries renewed on 2026-08-20.",
  },
  {
    assetCode: "AST-SND-02",
    name: "Behringer X32 Digital Sound Console",
    category: "Audio/Visual",
    location: "Main Stage Sound Booth",
    condition: "Good",
    status: "In Use",
    currentHolder: "Sound Department",
    notes: "Firmware updated to v4.06.",
  },
  {
    assetCode: "AST-KIT-01",
    name: "Commercial Stainless Steel Steam Cooker (50L)",
    category: "Utensils & Kitchen",
    location: "Mandir Main Kitchen",
    condition: "Good",
    status: "Available",
    notes: "Safety valve inspected this month.",
  },
  {
    assetCode: "AST-FUR-01",
    name: "Folding Banquet Chairs (Lot of 100)",
    category: "Furniture & Shamiyana",
    location: "Basement Store Room 2",
    condition: "Good",
    status: "Available",
  },
  {
    assetCode: "AST-PRJ-01",
    name: "Epson 5000 Lumens Full HD Laser Projector",
    category: "Audio/Visual",
    location: "Meeting Hall A",
    condition: "Excellent",
    status: "Available",
  },
];

export const initialRoomBookings = [
  {
    roomName: "Main Satsang Sabhagruh",
    purpose: "Sunday Evening Satsang Sabha",
    bookedBy: "Sabha Department",
    date: "2026-08-23",
    startTime: "17:00",
    endTime: "21:00",
    attendees: 180,
    status: "Confirmed",
  },
  {
    roomName: "Conference Hall B",
    purpose: "Janmashtami Planning Committee Meeting",
    bookedBy: "Nitinbhai Patel",
    date: "2026-08-24",
    startTime: "20:15",
    endTime: "21:30",
    attendees: 15,
    status: "Confirmed",
  },
  {
    roomName: "Dining Hall (Bhojanshala)",
    purpose: "Family Thal & Prasad Gathering",
    bookedBy: "Mukeshbhai Shah",
    date: "2026-08-29",
    startTime: "12:00",
    endTime: "15:00",
    attendees: 75,
    status: "Pending Approval",
  },
];

export const initialEvents = [
  {
    eventCode: "EVT-2026-JANM",
    title: "Shri Krishna Janmashtami Mahotsav 2026",
    gujaratiTitle: "શ્રીકૃષ્ણ જન્માષ્ટમી મહોત્સવ ૨૦૨૬",
    date: "2026-08-30",
    endDate: "2026-08-30",
    location: "HariPrabodham Mandir Ground, Nadiad",
    description: "Grand celebration with Bhajan Sandhya, Palna Darshan, cultural drama by youth, and midnight Mahaprasad.",
    capacity: 600,
    registeredCount: 420,
    status: "Live",
    committeeLeads: [
      { department: "Overall Coordinator", leadName: "Nitinbhai Patel" },
      { department: "Mahaprasad Kitchen", leadName: "Dipakbhai Shah" },
      { department: "Sound & Stage", leadName: "Devansh Patel" },
      { department: "Security & Gates", leadName: "Kiritbhai Desai" },
    ],
    tasks: [
      { id: "t1", title: "Palna floral decoration contract finalization", assignedTo: "Hansaben Patel", completed: true, dueDate: "2026-08-25" },
      { id: "t2", title: "Midnight Mahaprasad grocery delivery check", assignedTo: "Dipakbhai Shah", completed: true, dueDate: "2026-08-28" },
      { id: "t3", title: "Parking lot floodlights setup", assignedTo: "Kiritbhai Desai", completed: false, dueDate: "2026-08-29" },
      { id: "t4", title: "Live broadcast link generation and promotion", assignedTo: "Devansh Patel", completed: false, dueDate: "2026-08-29" },
    ],
  },
  {
    eventCode: "EVT-2026-YOUTH",
    title: "Annual Youth Seva & Leadership Shibir",
    gujaratiTitle: "વાર્ષિક યુવા સેવા શિબિર",
    date: "2026-09-12",
    endDate: "2026-09-13",
    location: "Anand Retreat Sabhagruh",
    description: "Two-day personality development, spiritual workshops, team-building seva challenges, and interaction with elders.",
    capacity: 150,
    registeredCount: 95,
    status: "Planning",
    committeeLeads: [
      { department: "Youth Lead", leadName: "Jaimin Trivedi" },
      { department: "Workshop Faculty", leadName: "Nitinbhai Patel" },
    ],
    tasks: [
      { id: "yt1", title: "Workbook & badge printing", assignedTo: "Jaimin Trivedi", completed: false, dueDate: "2026-09-05" },
      { id: "yt2", title: "Transportation bus booking from Nadiad", assignedTo: "Nitinbhai Patel", completed: false, dueDate: "2026-09-08" },
    ],
  },
];

export const initialThalSchedules = [
  {
    scheduleCode: "THAL-2026-0823-M",
    date: "2026-08-23",
    mealType: "Morning Thal",
    assignedFamilyName: "Patel Household (Rameshbhai)",
    assignedPhone: "9825056789",
    headcount: 45,
    status: "Completed",
    specialInstructions: "Puri, Shrikhand, Bataka nu Shaak, Dal Bhat.",
  },
  {
    scheduleCode: "THAL-2026-0823-E",
    date: "2026-08-23",
    mealType: "Evening Thal",
    assignedFamilyName: "Shah Family (Mukeshbhai)",
    assignedPhone: "9825098765",
    headcount: 50,
    status: "Confirmed",
    specialInstructions: "Khichdi, Kadhi, Ringan Bharta, Sukhdi.",
  },
  {
    scheduleCode: "THAL-2026-0824-M",
    date: "2026-08-24",
    mealType: "Morning Thal",
    assignedFamilyName: "Desai Family (Kiritbhai)",
    assignedPhone: "9825032109",
    headcount: 40,
    status: "Confirmed",
    specialInstructions: "Rotli, Paneer Bhurji, Chana Dal, Rice.",
  },
  {
    scheduleCode: "THAL-2026-0825-M",
    date: "2026-08-25",
    mealType: "Morning Thal",
    assignedFamilyName: "Bhatt Parivar (Pankajbhai)",
    assignedPhone: "9825011223",
    headcount: 45,
    status: "Assigned",
    specialInstructions: "Standard Satvik Morning Menu.",
  },
  {
    scheduleCode: "THAL-2026-0826-M",
    date: "2026-08-26",
    mealType: "Morning Thal",
    assignedFamilyName: "Trivedi Parivar (Hareshbhai)",
    assignedPhone: "9825076543",
    headcount: 40,
    status: "Declined",
    declineReason: "Family medical situation after surgery; requested date swap.",
    swapRequested: true,
  },
];

export const initialAnnouncements = [
  {
    title: "Important Update: Janmashtami Mahotsav Timings & Passes",
    gujaratiTitle: "મહત્વપૂર્ણ સૂચના: શ્રીકૃષ્ણ જન્માષ્ટમી મહોત્સવ સમય અને પાસ",
    body: "Please note that the evening Mahotsav on 30th August starts promptly at 5:30 PM. Download your digital QR pass from the HariSumiran App for swift entry.",
    gujaratiBody: "કૃપા કરીને નોંધ લેશો કે ૩૦ ઓગસ્ટના રોજ સાંજનો મહોત્સવ બરાબર ૫:૩૦ કલાકે શરૂ થશે. ઝડપી પ્રવેશ માટે હરિસુમિરન એપ પરથી તમારો ડિજિટલ QR પાસ મેળવો.",
    targetAudience: "Everyone",
    channels: ["App Push", "WhatsApp"],
    status: "Sent",
    authorName: "Nitinbhai Patel",
    approvedBy: "Pooja Swarupji",
    stats: { sentCount: 380, deliveredCount: 374, openedCount: 295 },
  },
  {
    title: "Kitchen Seva Volunteer Orientation for Sunday",
    gujaratiTitle: "રવિવાર માટે રસોઈ સેવા સ્વયંસેવક માર્ગદર્શન",
    body: "All Kitchen Seva volunteers are requested to arrive at the Mandir Bhojanshala by 4:00 PM for briefing with Dipakbhai Shah.",
    gujaratiBody: "બધા રસોઈ સેવા સ્વયંસેવકોને દીપકભાઈ શાહ સાથે મીટિંગ માટે બપોરે ૪:૦૦ વાગ્યે મંદિર ભોજનશાળામાં હાજર રહેવા વિનંતી છે.",
    targetAudience: "Kitchen Seva Volunteers",
    channels: ["App Push", "SMS"],
    status: "Sent",
    authorName: "Dipakbhai Shah",
    approvedBy: "Nitinbhai Patel",
    stats: { sentCount: 18, deliveredCount: 18, openedCount: 16 },
  },
];

export const initialAuditLogs = [
  {
    actorId: "usr-admin-01",
    actorName: "Nitinbhai Patel",
    actorRole: "mandir_admin",
    action: "UPDATE_THAL_ASSIGNMENT",
    module: "Thal Rotation",
    recordId: "THAL-2026-0824-M",
    description: "Assigned Desai Family for 24-Aug Morning Thal rotation.",
    createdAt: new Date(Date.now() - 3 * 3600000),
  },
  {
    actorId: "usr-karyakarta-01",
    actorName: "Jaimin Trivedi",
    actorRole: "karyakarta",
    action: "LOG_INTERACTION_NOTE",
    module: "Follow-Up",
    recordId: "CASE-NAD-101",
    description: "Added confidential visit plan for Trivedi Parivar surgery follow-up.",
    createdAt: new Date(Date.now() - 5 * 3600000),
  },
  {
    actorId: "usr-admin-01",
    actorName: "Nitinbhai Patel",
    actorRole: "mandir_admin",
    action: "BROADCAST_ANNOUNCEMENT",
    module: "Communication",
    recordId: "ANN-001",
    description: "Approved and broadcasted Janmashtami Mahotsav announcement to 380 recipients.",
    createdAt: new Date(Date.now() - 8 * 3600000),
  },
];
